version: "3.8"
services:
  outcome_frontend:
    container_name: football_outcome_frontend
    image: mehmood104/outcome:${app_version}
    build: ./outcome
    ports: 
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
      replicas: 5
  player_backend:
    container_name: football_player_backend
    image: mehmood104/player:${app_version}
    build: ./player
    deploy:
      replicas: 5
  team_backend:
    container_name: football_team_backend
    image: mehmood104/team:${app_version}
    build: ./team
    deploy:
      replicas: 5
  result_backend:
    container_name: football_result_backend
    image: mehmood104/result:${app_version}
    build: ./result
    deploy:
      replicas: 5